asset: cecil.phar
tap: Cecilapp/homebrew-cecil/Formula/cecil.rb
template: >
    class Cecil < Formula
        desc "Your content driven static site generator."
        homepage "$REPO_WEBITE"
        url "$STABLE_ASSET_URL"
        sha256 "$STABLE_ASSET_SHA256"
        version "$STABLE_VERSION"

        depends_on "php" if MacOS.version <= :el_capitan

        def install
            bin.install "cecil.phar" => "cecil"
        end

        test do
            shell_output("#{bin}/cecil --version").include?(version)
        end
    end
