filter:
  excluded_paths:
    - 'vendor/*'
    - 'tests/*'

tools:
  php_cs_fixer: true
  php_analyzer: true
  php_mess_detector: true
  php_changetracking: true
  php_code_sniffer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_code_coverage: false

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
