filter:
  excluded_paths:
    - 'dist/*'
    - 'resources/*'
    - 'tests/*'
  dependency_paths:
    - 'vendor/*'

tools:
  php_analyzer: true
  php_changetracking: true
  php_code_coverage: false
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR12
  php_cs_fixer:
    enabled: true
    config:
      level: psr12
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      before_parentheses:
        function_declaration: false
        closure_definition: true
      other:
        after_type_cast: true

build:
  environment:
    timezone: 'Europe/Paris'
    php:
      version: 8.3
      ini:
        xdebug.mode: coverage
        memory_limit: 2048M
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      requires:
        - node: analysis
        - branch: master
      tests:
        override:
          - command: ./vendor/bin/phpunit -c ./ --testsuite=IntegrationTests --coverage-text --coverage-clover=build/logs/clover.xml
            idle_timeout: 360
            coverage:
              file: build/logs/clover.xml
              format: clover
