filter:
  excluded_paths:
  - 'dist/*'
  - 'resources/*'
  - 'tests/*'
  dependency_paths:
  - 'vendor/*'

tools:
  php_analyzer: true
  php_changetracking: true
  php_code_coverage: false
  php_code_sniffer: true
  php_cs_fixer: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

build:
  environment:
    timezone: 'Europe/Paris'
    php:
      version: 7.4
      compile_options: '--with-config-file-path=/home/scrutinizer/.phpenv/versions/7.4.27/etc --with-config-file-scan-dir=/home/scrutinizer/.phpenv/versions/7.4.27/etc/conf.d --prefix=/home/scrutinizer/.phpenv/versions/7.4.27 --libexecdir=/home/scrutinizer/.phpenv/versions/7.4.27/libexec --enable-intl --with-openssl --with-gd --enable-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-exif --with-libzip --with-zlib --with-zlib-dir=/usr --enable-xmlreader --with-xsl --enable-pcntl --with-readline --enable-mbstring --with-curl --with-gettext --with-bz2 --enable-bcmath --with-libdir=lib --with-pear=/home/scrutinizer/.phpenv/versions/7.4.27/pear --with-webp-dir=/usr'
  nodes:
    analysis:
      #requires:
      #- is_pull_request: true
      tests:
        override:
        - php-scrutinizer-run
    coverage:
      requires:
      - node: analysis
      - branch: master
      tests:
        override:
        - command: ./vendor/bin/phpunit -c ./ --testsuite=IntegrationTests --coverage-text --coverage-clover=build/logs/clover.xml
          idle_timeout: 360
          coverage:
            file: build/logs/clover.xml
            format: clover
