filter:
  excluded_paths:
    - 'dist/*'
    - 'resources/*'
    - 'tests/*'
  dependency_paths:
    - 'vendor/*'

tools:
  php_analyzer: true
  php_changetracking: true
  php_code_coverage: false
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR12
  php_cs_fixer:
    enabled: true
    config:
      level: psr12
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      before_parentheses:
        function_declaration: false
        closure_definition: true
      other:
        after_type_cast: true

build:
  #image: default-bionic
  environment:
    timezone: 'Europe/Paris'
    php:
      version: 8.2
      #compile_options: '--with-config-file-path=/home/scrutinizer/.phpenv/versions/7.4.27/etc --with-config-file-scan-dir=/home/scrutinizer/.phpenv/versions/7.4.27/etc/conf.d --prefix=/home/scrutinizer/.phpenv/versions/7.4.27 --libexecdir=/home/scrutinizer/.phpenv/versions/7.4.27/libexec --enable-intl --with-openssl --with-gd --enable-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-exif --with-libzip --with-zlib --with-zlib-dir=/usr --enable-xmlreader --with-xsl --enable-pcntl --with-readline --enable-mbstring --with-curl --with-gettext --with-bz2 --enable-bcmath --with-libdir=lib --with-pear=/home/scrutinizer/.phpenv/versions/7.4.27/pear --with-webp-dir=/usr -with-vpx-dir=/usr'
      ini:
        xdebug.mode: coverage
        memory_limit: 2048M
  nodes:
    analysis:
      #requires:
      #  - is_pull_request: true
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      requires:
        - node: analysis
        - branch: master
      tests:
        override:
          - command: ./vendor/bin/phpunit -c ./ --testsuite=IntegrationTests --coverage-text --coverage-clover=build/logs/clover.xml
            idle_timeout: 360
            coverage:
              file: build/logs/clover.xml
              format: clover
