filter:
  excluded_paths:
  - 'dist/*'
  - 'resources/*'
  - 'tests/*'
  dependency_paths:
  - 'vendor/*'

tools:
  php_analyzer: true
  php_changetracking: true
  php_code_coverage: false
  php_code_sniffer: true
  php_cs_fixer: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

build:
  environment:
    timezone: 'Europe/Paris'
  nodes:
    analysis:
      requires:
      - is_pull_request: true
      tests:
        override:
        - php-scrutinizer-run
    coverage:
      requires:
      - branch: master
      tests:
        override:
        - command: ./vendor/bin/phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
          coverage:
            file: build/logs/clover.xml
            format: clover
