php_version: 8.1
commit_failure_conditions:
    - "project.severity.critical > 0"
global_exclude_dirs:
    - dist
    - docs
    - tests
exclude_patterns:
    - .*
    - resources/server/router.php
    - resources/skeleton/static/*
rules:
    missing_e_o_l:
      enabled: false
    # temp
    php.invalid_return_typehint:
        enabled: false
    php.invalid_typehint:
        enabled: false
