version: 2
jobs:
  build:
    docker:
    - image: cimg/php:8.3
    steps:
    - run:
        name: Switch timezone to Europe/Paris
        command: sudo cp /usr/share/zoneinfo/Europe/Paris /etc/localtime
    - checkout
    - restore_cache:
        keys:
          - composer-{{ checksum "composer.lock" }}
          #- composer- # fallback
    - run:
        name: Install PHP dependencies
        command: |
          sudo composer self-update
          composer install -n --prefer-source
    - save_cache:
        key: composer-{{ checksum "composer.lock" }}
        paths:
          - ./vendor
    - run:
        name: Run tests
        command: |
          mkdir -p ~/phpunit
          vendor/bin/phpunit --testsuite=IntegrationTests --log-junit=~/phpunit/junit.xml
        when: always
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
