version: 2.1
jobs:
  build:
    docker:
    - image: cimg/php:8.3
    steps:
    - run:
        name: Switch timezone to Europe/Paris
        command: sudo cp /usr/share/zoneinfo/Europe/Paris /etc/localtime
    - run:
        name: Checkout code
        command: |
          git clone "https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" .
          git checkout -q "$CIRCLE_SHA1"
        no_output_timeout: 5m
    - restore_cache:
        keys:
          - composer-{{ checksum "composer.lock" }}
          #- composer- # fallback
    - run:
        name: Install PHP dependencies
        command: |
          sudo composer self-update
          composer install -n --prefer-source
        no_output_timeout: 10m
    - save_cache:
        key: composer-{{ checksum "composer.lock" }}
        paths:
          - ./vendor
    - run:
        name: Run tests
        command: |
          mkdir -p ~/phpunit
          vendor/bin/phpunit --testsuite=IntegrationTests --log-junit=~/phpunit/junit.xml
        when: always
        no_output_timeout: 20m
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
