blank_issues_enabled: true
contact_links:
  - name: Cecil documentation
    url: https://cecil.app/documentation/
    about: Please read the documentation before submitting a bug or a feature request.
