name: CI

on:
  push:
    #branches: [ $default-branch ]
  pull_request:
    #branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
        experimental: [false]
        include:
        - php-versions: '8.0'
          experimental: true
    name: PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: |
            vendor
            themes
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test
#
#  deploy:
#
#    runs-on: ubuntu-latest
#    name: Deploy
#    needs: build
#
#    steps:
#      - name: Download result for job 1
#        uses: actions/download-artifact@v1
#        with:
#          name: xxx
