name: Tag to Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

jobs:
  build:
    name: Create a release on tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check if prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_name }}" =~ -(alpha|beta)\.[0-9]+$ ]]; then
            echo "value=true" >> "$GITHUB_OUTPUT"
          else
            echo "value=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: ${{ steps.prerelease.outputs.value == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
