name: 'Tag'

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Create release on tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
